config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'bio', to: 'pages#bio'
  resources :artworks
  resources :phases
  resources :shows
  resources :lives
  resources :writings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  has_one_attached :photo
  # belongs_to :phase

  validates :title, presence: true
  validates :year, presence: true
  validates :height, presence: true
  validates :width, presence: true
  validates :depth, presence: true
  validates :technique, presence: true
  validates :about, presence: true
  validates :description, presence: true
  validates :period, presence: true
end

app/models/live.rb
class Live < ApplicationRecord
end

app/models/phase.rb
class Phase < ApplicationRecord
  has_many :artworks
end

app/models/show.rb
class Show < ApplicationRecord
end

app/models/writing.rb
class Writing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artworks

  def index
  end

  def show
    @artwork = Artwork.find(params[:id])
  end

  private

  def set_artworks
    @artworks = Artwork.all
  end
end

app/controllers/lives_controller.rb
class LivesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  private

  def set_artworks
    @artworks = Artwork.all
  end
end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  before_action :set_phases

  def index
  end

  def show
    @phase = Phase.find(params[:id])
  end

  private
  def set_phases
    @phases = Phase.all
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_shows

  def index
  end

  def show
    @show = Show.find(params[:id])
  end

  private
  def set_shows
    @shows = Show.all
  end
end

app/controllers/writings_controller.rb
class WritingsController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artworks/index.html.erb
<% @artworks.each do |artwork| %>
  <%= artwork.title %>
  <%= artwork.year %>
  <%= artwork.technique %>
  <%= artwork.width %> x <%= artwork.height %> x <%= artwork.depth %>
<% end %>

app/views/artworks/show.html.erb
<%= link_to artworks_path do %>
  <h3>vovler a obras</h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alberto Greco</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta charset="UTF-8">
  <link rel="stylesheet" href="styles.css">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  <%= favicon_link_tag asset_path('favicon.png') %>
</head>

<body>

  <div class="text-gray-600">

    <% if content_for? :navbar %>
      <%= yield %>
    <% else %>
      <div class="p-5">
        <div class="flex border-b pb-4 justify-between">

          <%= link_to root_path do %>
          <h1 class="text-5xl text-gray-900"><strong>ALBERTO GRECO</strong></h1>
          <% end %>

          <div class="flex pt-3">
            <p class="px-2 hover:text-gray-1000"><%= link_to "BIOGRAFIA", bio_path %></p>
            <p class="px-2 hover:text-gray-1000"><%= link_to "ETAPAS", phases_path %></p>
            <p class="px-2 hover:text-gray-1000"><%= link_to "OBRAS", artworks_path %></p>
            <p class="px-2 hover:text-gray-1000"><%= link_to "MUESTRAS", shows_path %></p>
            <p class="px-2 hover:text-gray-1000"><%= link_to "ARTE VIVO", lives_path %></p>
            <p class="px-2 hover:text-gray-1000"><%= link_to "ESCRITOS", writings_path %></p>
          </div>

        </div>

        <div class="py-3">

        </div>


        <%= yield %>
      </div>
    <% end %>

      <%= render 'shared/footer' %>

  </div>


</body>
</html>

app/views/lives/index.html.erb
<h1>Lives#index</h1>
<p>Find me in app/views/lives/index.html.erb</p>

app/views/lives/show.html.erb
<h1>Lives#show</h1>
<p>Find me in app/views/lives/show.html.erb</p>

app/views/pages/bio.html.erb
<%= content_for :navbar do %>
""
<% end %>


<div class="flex pt-7 pl-3">

  <div class="">
    <p class="px-2 hover:text-yellow-300"><%= link_to "GRECO", root_path %></p>
    <p class="px-2 hover:text-yellow-300"><%= link_to "BIOGRAFIA", bio_path %></p>
    <p class="px-2 hover:text-yellow-300"><%= link_to "ETAPAS", phases_path %></p>
    <!--             <li class="px-2 hover:text-yellow-300"><%= link_to "OBRAS", artworks_path %></li> -->
    <p class="px-2 hover:text-yellow-300"><%= link_to "MUESTRAS", shows_path %></p>
<!--             <li class="px-2 hover:text-yellow-300"><%= link_to "ARTE VIVO", lives_path %></li>
  <li class="px-2 hover:text-yellow-300"><%= link_to "ESCRITOS", writings_path %></li> -->
  </div>

  <div>
    <div class="">
      <h4 class="pb-2 ">Alberto Greco nace en Buenos Aires, Argentina en 1931 y es reconocido como uno de los pioneros de la vanguardia informalista argentina al integrar en 1959 el Movimiento Informalista Argentino.
        En 1961 realiza su última muestra de pinturas en Buenos Aires en la galería Pizarro, en la cual presenta la serie Las Mojas.
        Poco después se instala en Paris donde realiza, en 1962, la Primera Exposición de Arte Vivo, “firmando” personas.
        En 1963 viaja a Piedralaves en Ávila, España, donde realiza la serie de acciones fotografiadas por Montserrat Santamaría.
        En Génova, en ese mismo año, publica el Manifiesto Dito dell’Arte Vivo en italiano.
        En 1964, expone en la galería Juana Mordó en Madrid y regresa a Buenos Aires, donde presenta su experiencia de Arte Vivo: Mi Madrid querido. Pintura espectáculo Vivo-Dito, con colaboración del bailarín Antonio Gades.
      En 1965, se instala en Barcelona, ciudad en la cual se quita la vida.</h4>
    </div>

    <h2 class="py-2 text-3xl border-r pr-8">TRAYECTORIA</h2>

    <div class="py-2">
      <h3 class="font-bold">1947-48</h3>
      <h4>Asiste a los talleres de Cecilia Marcovich y Tomas Maldonado.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1954</h3>
      <h4>Beca del Gobierno Francés para mudarse a París.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1955</h3>
      <h4>Expone en la galería La Roue - París, Francia.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1956</h3>
      <h4>Regresa a Buenos Aires y expone en la galería Antígona.</h4>
      <h4>Expone en la galería Petit Galerie – Río de Janeiro, Brasil.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1958</h3>
      <h4>Expone en Museo de Arte Moderno – Sao Paulo, Brasil.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1958</h3>
      <h4><strong>Premio</strong> Adquisición del Estado de San Pablo en pintura.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1959</h3>
      <h4>Integra Movimiento Informalista con Kenneth Kemble, López, Maza, Martha Pucciarelli, y Luis Wells, entre otros.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1959</h3>
      <h4>Movimiento Informalista. Galería Van Riel – Buenos Aires, Argentina.</h4>
      <h4>Informalismo. Galería Pizarro – Buenos Aires, Argentina.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1960</h3>
      <h4>Expone en Galería Pizarro – Buenos Aires, Argentina.</h4>
      <h4>Participa en VI Salón Anual de Arte Nuevo. Museo Eduardo Sívori – Buenos Aires, Argentina.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1960</h3>
      <h4><strong>Premio</strong> de público de Ridder.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1961</h3>
      <h4>Las Monjas. Galería Pizarro – Buenos Aires, Argentina.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1962</h3>
      <h4>Pablo (Curatella) Manes y 30 artistas argentinos de Nueva Generación. Galería Creuze Messine – París, Francia.</h4>
    </div>

    <div class="py-2">
      <h3 class="font-bold">1964</h3>
      <h4>Expone en Galería Juana Mordó – Madrid, España.</h4>
    </div>

</div>



</div>

<div class="flex py-4">

  <div class="mr-4 text-right">
    <div class="py-2">
      <h3 class="font-bold">1996</h3>
      <h4>Alberto Greco. Obras extraviadas. Centro Cultural Borges – Buenos Aires, Argentina.</h4>
    </div>
    <div class="py-2">
      <h3 class="font-bold">1992</h3>
      <h4>Alberto Greco. Museo Nacional de Bellas Arte – Buenos Aires, Argentina.</h4>
    </div>
    <div class="py-2">
      <h3 class="font-bold">1991</h3>
      <h4>Alberto Greco. IVAM Centro Julio González – Valencia, España.</h4>
    </div>
    <div class="py-2">
      <h3 class="font-bold">1988</h3>
      <h4>Alberto Greco y Rubén Santatonín. Fundación San Telmo – Buenos Aires, Argentina.</h4>
    </div>
    <div class="py-2">
      <h3 class="font-bold">1987</h3>
      <h4>Alberto Greco a cinco anos de su muerte. Galería Carmen Waugh – Buenos Aires, Argentina.</h4>
    </div>
    <div class="py-2">
      <h3 class="font-bold">1967</h3>
      <h4>Salón de Jeune Peinture -  París, Francia.</h4>
    </div>
    <div class="py-2">
      <h3 class="font-bold">1965</h3>
      <h4>Homenaje a Alberto Greco. Galería Pizarro – Buenos Aires, Argentina.</h4>
    </div>
  </div>

  <h2 class="py-2 text-3xl border-l pl-8 w-1/3">EXHIBICIONES PÓSTUMAS</h2>
</div>

<div class="text-center pt-6">
  <h2 class="py-2 text-3xl">COLECCIONES PÚBLICAS</h2>
  <h3>Museo de Arte Contemporáneo de Rosario – <i>Rosario, Argentina</i></h3>
  <h3>Museo de Arte Moderno de Buenos Aires – <i>Buenos Aires, Argentina</i></h3>
  <h3>Museo Nacional de Bellas Arte – <i>Buenos Aires, Argentina</i></h3>
  <h3>Museum of Modern Art - <i>Nueva York, Estados Unidos</i></h3>
  <h3>Fundación Federico Jorge Klemm – <i>Buenos Aires, Argentina</i></h3>
  <h3>Museo Nacional Centro de Arte Reina Sofía – <i>Madrid, España</i></h3>
</div>

</div>

<!-- <div class="w-2/5">
  <div class="float-right sm:float-none md:float-right ml-20">
    <%= image_tag asset_path('alberto1.jpg') %>
  </div>
  <div class="float-right sm:float-none md:float-right ml-20">
    <%= image_tag asset_path('alberto.jpg') %>
  </div>
  <div class="float-right sm:float-none md:float-right ml-20">
    <%= image_tag asset_path('alberto1.jpg') %>
  </div>
  <div class="float-right sm:float-none md:float-right ml-20">
    <%= image_tag asset_path('alberto.jpg') %>
  </div>
</div> -->

</div>

app/views/pages/home.html.erb
<%= content_for :navbar do %>
  ""
<% end %>

<!-- <div class="flex justify-between p-5">

  <%= link_to root_path do %>
    <h1 class="text-5xl text-gray-900"><strong>ALBERTO GRECO</strong></h1>
  <% end %>

  <ol class="flex pt-3">
    <p class="px-2 hover:text-gray-900"><%= link_to "BIOGRAFIA", bio_path %></p>
    <li class="px-2 hover:text-gray-900"><%= link_to "ETAPAS", phases_path %></li>
    <li class="px-2 hover:text-gray-900"><%= link_to "OBRAS", artworks_path %></li>
    <li class="px-2 hover:text-gray-900"><%= link_to "MUESTRAS", shows_path %></li>
    <li class="px-2 hover:text-gray-900"><%= link_to "ARTE VIVO", lives_path %></li>
    <li class="px-2 hover:text-gray-900"><%= link_to "ESCRITOS", writings_path %></li>
  </ol>
</div> -->

<!-- <div class="px-0">
 <%= image_tag asset_path('nascimiento.jpg') %>
</div> -->

<nav>
  <header>
    <div class="pt-3 flex justify-center">
      <p class="px-2 hover:text-yellow-300"><%= link_to "GRECO", root_path %></p>
      <p class="px-2 hover:text-yellow-300"><%= link_to "BIOGRAFIA", bio_path %></p>
      <p class="px-2 hover:text-yellow-300"><%= link_to "ETAPAS", phases_path %></p>
      <!-- <p class="px-2 hover:text-yellow-300"><%= link_to "OBRAS", artworks_path %></p> -->
      <p class="px-2 hover:text-yellow-300"><%= link_to "MUESTRAS", shows_path %></p>
<!--       <p class="px-2 hover:text-yellow-300"><%= link_to "ARTE VIVO", lives_path %></p>
      <p class="px-2 hover:text-yellow-300"><%= link_to "ESCRITOS", writings_path %></p> -->
    </div>
  </header>
</nav>

<div class="flex">

  <div class="left w-1/2">
    <div style="height: 1800px;">
      <div>
        <%= image_tag asset_path('nun2.png') %>
      </div>
      <div>
        <%= image_tag asset_path('dorso.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('fiesta.jpg') %>
      </div>
    </div>
  </div>

  <div class="right w-1/2">
    <div style="height: 1800px;">
      <div>
        <%= image_tag asset_path('nascimiento.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('sos.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('grande.jpg') %>
      </div>
    </div>
  </div>

</div>

app/views/pages/welcome.html.erb
<%= content_for :navbar do %>
  ""
<% end %>

<!-- <div class="flex justify-between p-5">

  <%= link_to root_path do %>
    <h1 class="text-5xl text-gray-900"><strong>ALBERTO GRECO</strong></h1>
  <% end %>

  <ol class="flex pt-3">
    <p class="px-2 hover:text-gray-900"><%= link_to "BIOGRAFIA", bio_path %></p>
    <li class="px-2 hover:text-gray-900"><%= link_to "ETAPAS", phases_path %></li>
    <li class="px-2 hover:text-gray-900"><%= link_to "OBRAS", artworks_path %></li>
    <li class="px-2 hover:text-gray-900"><%= link_to "MUESTRAS", shows_path %></li>
    <li class="px-2 hover:text-gray-900"><%= link_to "ARTE VIVO", lives_path %></li>
    <li class="px-2 hover:text-gray-900"><%= link_to "ESCRITOS", writings_path %></li>
  </ol>
</div> -->

<!-- <div class="px-0">
 <%= image_tag asset_path('nascimiento.jpg') %>
</div> -->

<nav>
  <header>
    <div class="pt-3 flex justify-center">
      <p class="px-2 hover:text-yellow-300"><%= link_to "GRECO", root_path %></p>
      <p class="px-2 hover:text-yellow-300"><%= link_to "BIOGRAFIA", bio_path %></p>
      <p class="px-2 hover:text-yellow-300"><%= link_to "ETAPAS", phases_path %></p>
      <!-- <p class="px-2 hover:text-yellow-300"><%= link_to "OBRAS", artworks_path %></p> -->
      <p class="px-2 hover:text-yellow-300"><%= link_to "MUESTRAS", shows_path %></p>
<!--       <p class="px-2 hover:text-yellow-300"><%= link_to "ARTE VIVO", lives_path %></p>
      <p class="px-2 hover:text-yellow-300"><%= link_to "ESCRITOS", writings_path %></p> -->
    </div>
  </header>
</nav>

<div class="flex">

  <div class="left w-1/2">
    <div style="height: 1800px;">
      <div>
        <%= image_tag asset_path('nun2.png') %>
      </div>
      <div>
        <%= image_tag asset_path('dorso.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('fiesta.jpg') %>
      </div>
    </div>
  </div>

  <div class="right w-1/2">
    <div style="height: 1800px;">
      <div>
        <%= image_tag asset_path('nascimiento.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('sos.jpg') %>
      </div>
      <div>
        <%= image_tag asset_path('grande.jpg') %>
      </div>
    </div>
  </div>

</div>

app/views/phases/index.html.erb
<%= content_for :navbar do %>
""
<% end %>


<div class="flex">

  <div class="flex-none">
    <div class="left">

      <div class="flex">

        <div class="">
          <ol class="pt-7 px-3">
            <p class="px-2 hover:text-yellow-300"><%= link_to "GRECO", root_path %></p>
            <p class="px-2 hover:text-yellow-300"><%= link_to "BIOGRAFIA", bio_path %></p>
            <li class="px-2 hover:text-yellow-300"><%= link_to "ETAPAS", phases_path %></li>
<!--             <li class="px-2 hover:text-yellow-300"><%= link_to "OBRAS", artworks_path %></li> -->
            <li class="px-2 hover:text-yellow-300"><%= link_to "MUESTRAS", shows_path %></li>
<!--             <li class="px-2 hover:text-yellow-300"><%= link_to "ARTE VIVO", lives_path %></li>
            <li class="px-2 hover:text-yellow-300"><%= link_to "ESCRITOS", writings_path %></li> -->
          </ol>
        </div>

        <div class="bg-gray-100 h-screen px-5 pt-7">
<!--           <% @phases.each do |phase| %>
            <h3 class="hover:text-yellow-300">
              <%= link_to phase_path(phase) do %>
                <%= phase.title %>
              <% end %>
            </h3>
          <% end %> -->

          <h1 class="hover:text-yellow-300">PRIMERA ETAPA</h1>
<!--           <div class="hover-image">
            <%= image_tag asset_path('nun2.png') %>
          </div> -->

          <h1 class="hover:text-yellow-300"><%= link_to "INFORMALISMO", @phases.phase_path(id: 17) %></h1>
          <h1 class="hover:text-yellow-300">LA EXPOSICION RODANTE</h1>
          <h1 class="hover:text-yellow-300">LAS MONJAS  </h1>
          <h1 class="hover:text-yellow-300">LA VIDA SOBRE PAPEL</h1>
          <h1 class="hover:text-yellow-300">ARTE VIVO</h1>
          <h1 class="hover:text-yellow-300">COLLAGE</h1>
          <h1 class="hover:text-yellow-300">ESCRITOS</h1>

        </div>

      </div>

    </div>
  </div>

  <div class="flex-grow">
    <div class="right">
      <div style="height: 1800px;">
        <%= image_tag asset_path('fiesta.jpg') %>
      </div>
    </div>
  </div>

</div>









<!-- <div class="h-screen">
  <% @phases.each do |phase| %>
    <h3 class="text-3xl py-1 hover:underline">
      <%= link_to phase_path(phase) do %>
        <%= phase.title %>
      <% end %>
    </h3>
  <% end %>
  <div class="pt-6">
    <svg class="animate-bounce w-6 h-6 text-gray-900" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
      <path d="M19 14l-7 7m0 0l-7-7m7 7V3"></path>
    </svg>
  </div>
</div>
-->

app/views/phases/show.html.erb
<%= content_for :navbar do %>
""
<% end %>


<div class="flex">

  <div class="flex-none">
    <div class="left">

      <div class="flex">
          <ol class="pt-7 pl-3">
            <p class="px-2 hover:text-yellow-300"><%= link_to "GRECO", root_path %></p>
            <p class="px-2 hover:text-yellow-300"><%= link_to "BIOGRAFIA", bio_path %></p>
            <li class="px-2 hover:text-yellow-300"><%= link_to "ETAPAS", phases_path %></li>
            <!-- <li class="px-2 hover:text-yellow-300"><%= link_to "OBRAS", artworks_path %></li> -->
            <li class="px-2 hover:text-yellow-300"><%= link_to "MUESTRAS", shows_path %></li>
<!--             <li class="px-2 hover:text-yellow-300"><%= link_to "ARTE VIVO", lives_path %></li>
            <li class="px-2 hover:text-yellow-300"><%= link_to "ESCRITOS", writings_path %></li> -->
          </ol>

          <div class="bg-gray-100 h-screen pl-5 pt-7">
            <% @phases.each do |phase| %>
              <h3 class="hover:text-yellow-300">
                <%= link_to phase_path(phase) do %>
                <%= phase.title %>
                <% end %>
              </h3>
            <% end %>
          </div>

      </div>
    </div>
  </div>

  <div class="flex-grow">
    <div class="right">
      <div style="height: 1800px;">
        <div>
          <%= image_tag asset_path('nascimiento.jpg') %>
        </div>
        <div>
          <%= image_tag asset_path('sos.jpg') %>
        </div>
        <div>
          <%= image_tag asset_path('grande.jpg') %>
        </div>
      </div>
    </div>
  </div>

</div>



  <!-- <div class="flex" style="width: 25%;"> -->

<!--     <div>

      <div class="flex vertical-menu">
        <p class="px-2 hover:text-yellow-300 flex-1"><%= link_to "GRECO", root_path %></p>
        <p class="px-2 hover:text-yellow-300 flex-1"><%= link_to "BIOGRAFIA", bio_path %></p>
        <p class="px-2 hover:text-yellow-300 flex-1"><%= link_to "ETAPAS", phases_path %></p>
        <p class="px-2 hover:text-yellow-300 flex-1"><%= link_to "OBRAS", artworks_path %></p>
        <p class="px-2 hover:text-yellow-300 flex-1"><%= link_to "MUESTRAS", shows_path %></p>
        <p class="px-2 hover:text-yellow-300 flex-1" style="width: 100px;"><%= link_to "ARTE VIVO", lives_path %></p>
        <p class="px-2 hover:text-yellow-300 flex-1"><%= link_to "ESCRITOS", writings_path %></p>
      </div>

      <div>
        <div class="bg-gray-100 h-screen pl-5 pt-7">
          <% @phases.each do |phase| %>
            <h3 class="hover:text-yellow-300">
              <%= link_to phase_path(phase) do %>
                <%= phase.title %>
              <% end %>
            </h3>
          <% end %>
        </div>
      </div>

    </div> -->

app/views/shared/_footer.html.erb
<!-- <div class="p-5">
  <div class="footer bg-white relative pt-1 mb-3">
    <div class="sm:flex sm:mt-6">
      <div class="sm:mt-0 sm:w-full flex flex-col md:flex-row">
          <div class="flex">
            <span class="px-2"><a href="https://www.instagram.com/vivodito/" class="text-blue-700  text-md hover:text-blue-500"><i class="fab fa-instagram"></i></a></span>
            <span class="px-2"><a href="https://twitter.com/vivodito" class="text-blue-700  text-md hover:text-blue-500"><i class="fab fa-twitter"></i></a></span>
            <span class="px-2"><a href="https://www.facebook.com/vivoditoarte" class="text-blue-700  text-md hover:text-blue-500"><i class="fab fa-facebook"></i></a></span>
          </div>
      </div>
    </div>
  </div>

  <footer class="footer bg-white relative pt-1 border-t">
      <div class="mx-auto">
        <div class="sm:flex sm:mt-6">
            <div class="sm:mt-0 sm:w-full flex flex-col md:flex-row justify-between items-end">
              <div class="flex flex-col">
                <span class="text-gray-700 mb-2 text-xs">C1014CD buenos aires, argentina</span>
              </div>
              <p class="text-gray-600 mb-2 text-xs"> © 2021 by MICAELA JENIK</p>
            </div>
        </div>
      </div>
  </footer>
</div>
 -->

app/views/shows/index.html.erb
<%= content_for :navbar do %>
""
<% end %>


<div class="flex pt-7 pl-3">

  <div class="">
    <p class="px-2 hover:text-yellow-300"><%= link_to "GRECO", root_path %></p>
    <p class="px-2 hover:text-yellow-300"><%= link_to "BIOGRAFIA", bio_path %></p>
    <p class="px-2 hover:text-yellow-300"><%= link_to "ETAPAS", phases_path %></p>
    <!--             <li class="px-2 hover:text-yellow-300"><%= link_to "OBRAS", artworks_path %></li> -->
    <p class="px-2 hover:text-yellow-300"><%= link_to "MUESTRAS", shows_path %></p>
<!--             <li class="px-2 hover:text-yellow-300"><%= link_to "ARTE VIVO", lives_path %></li>
  <li class="px-2 hover:text-yellow-300"><%= link_to "ESCRITOS", writings_path %></li> -->
  </div>

  <div>
    <% @shows.each do |show| %>

      <h1><%= show.title %></h1>
      <h1><%= show.year %></h1>
      <h1><%= show.place %></h1>
      <h1><%= show.city %></h1>
      <h1><%= show.country %></h1>
    <% end %>
  </div>

</div>

app/views/shows/show.html.erb
<%= link_to shows_path do %>
  <h3>vovler a muestras</h3>
<% end %>

app/views/writings/index.html.erb
<h1>Writings#index</h1>
<p>Find me in app/views/writings/index.html.erb</p>

app/views/writings/show.html.erb
<h1>Writings#show</h1>
<p>Find me in app/views/writings/show.html.erb</p>